version: 0.1

phases:
  pre_build:
    commands:
      - echo ${CODEBUILD_SOURCE_VERSION}
      - ./gradlew clean

  build:
    commands:
      - ./gradlew build

artifacts:
  files:
    - build/libs/super-hunassy-1.0.jar
    - build/reports/**/*
    - build/test-results/test/*.xml
