---
server:
  port: 8080

spring:
  application:
    name: super-hunassy

  datasource:
    dbcp2:
      url: jdbc:h2:mem:test;MODE=MYSQL
      username: sa
      password: ""

liquibase:
  enabled: false

hunassy:
  name: HogeHoge
  age: 17
